version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    depends_on:
      - addition-service
      - subtraction-service
      - multiplication-service
      - division-service
      - gcd-service
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addition-service:
    build: ./addition
    hostname: addition-service
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - addition

  subtraction-service:
    build: ./subtraction
    hostname: subtraction-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - subtraction

  multiplication-service:
    build: ./multiplication
    hostname: multiplication-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - multiplication
  
  division-service:
    build: ./division
    hostname: division-service
    ports:
      - 5054:5054
    networks:
      sample:
        aliases:
          - division

  gcd-service:
    build: ./gcd
    hostname: gcd-service
    ports:
      - 5055:5055
    networks:
      sample:
        aliases:
          - gcd
  
  lcm-service:
    build: ./lcm
    hostname: lcm-service
    ports:
      - 5056:5056
    networks:
      sample:
        aliases:
          - lcm

  modulus-service:
    build: ./modulus
    hostname: modulus-service
    ports:
      - 5057:5057
    networks:
      sample:
        aliases:
          - modulus

  exponent-service:
    build: ./exponent
    hostname: exponent-service
    ports:
      - 5058:5058
    networks:
      sample:
        aliases:
          - exponent

  greater_than-service:
    build: ./greater_than
    hostname: greater_than-service
    ports:
      - 5059:5059
    networks:
      sample:
        aliases:
          - greater_than
  
  less_than-service:
    build: ./less_than
    hostname: less_than-service
    ports:
      - 5060:5060
    networks:
      sample:
        aliases:
          - less_than
  
  equal-service:
    build: ./equal
    hostname: equal-service
    ports:
      - 5061:5061
    networks:
      sample:
        aliases:
          - equal
  
  sine-service:
    build: ./sine
    hostname: sine-service
    ports:
      - 5062:5062
    networks:
      sample:
        aliases:
          - sine
  
  cosine-service:
    build: ./cosine
    hostname: cosine-service
    ports:
      - 5063:5063
    networks:
      sample:
        aliases:
          - cosine
networks:
  sample:
